export const checkForDuplicates = (inputArray: string[]): boolean => {
    return new Set(inputArray).size !== inputArray.length;
  }
//from https://emailregex.com/
export const emailRegex = /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/;


export type GenericObject = {[key: string | number]: any};
// NOTE: there's a couple of weird cases where passing the key as a function is necessary, but we may be able to remove this later
export const getEntry = <ItemType extends GenericObject,>(arr: ItemType[], id: any, key: string | number | Function ='id'): ItemType => {
  let match = arr.find(a => (typeof key === 'function')? key(a) == id : a[key] == id)
  if(match === undefined){
    throw new Error("Couldn't find match in array!")
  }
  return match
}

export const urlRegex = /^(http|https):\/\/[^ "]+$/;
export const timeZones = [
  'Pacific/Midway',
  'Pacific/Pago_Pago',
  'Pacific/Honolulu',
  'America/Anchorage',
  'America/Vancouver',
  'America/Los_Angeles',
  'America/Tijuana',
  'America/Edmonton',
  'America/Denver',
  'America/Phoenix',
  'America/Mazatlan',
  'America/Winnipeg',
  'America/Regina',
  'America/Chicago',
  'America/Mexico_City',
  'America/Guatemala',
  'America/El_Salvador',
  'America/Managua',
  'America/Costa_Rica',
  'America/Montreal',
  'America/New_York',
  'America/Indianapolis',
  'America/Panama',
  'America/Bogota',
  'America/Lima',
  'America/Halifax',
  'America/Puerto_Rico',
  'America/Caracas',
  'America/Santiago',
  'America/St_Johns',
  'America/Montevideo',
  'America/Araguaina',
  'America/Argentina/Buenos_Aires',
  'America/Godthab',
  'America/Sao_Paulo',
  'Atlantic/Azores',
  'Canada/Atlantic',
  'Atlantic/Cape_Verde',
  'UTC',
  'Etc/Greenwich',
  'Europe/Belgrade',
  'CET',
  'Atlantic/Reykjavik',
  'Europe/Dublin',
  'Europe/London',
  'Europe/Lisbon',
  'Africa/Casablanca',
  'Africa/Nouakchott',
  'Europe/Oslo',
  'Europe/Copenhagen',
  'Europe/Brussels',
  'Europe/Berlin',
  'Europe/Helsinki',
  'Europe/Amsterdam',
  'Europe/Rome',
  'Europe/Stockholm',
  'Europe/Vienna',
  'Europe/Luxembourg',
  'Europe/Paris',
  'Europe/Zurich',
  'Europe/Madrid',
  'Africa/Bangui',
  'Africa/Algiers',
  'Africa/Tunis',
  'Africa/Harare',
  'Africa/Nairobi',
  'Europe/Warsaw',
  'Europe/Prague',
  'Europe/Budapest',
  'Europe/Sofia',
  'Europe/Istanbul',
  'Europe/Athens',
  'Europe/Bucharest',
  'Asia/Nicosia',
  'Asia/Beirut',
  'Asia/Damascus',
  'Asia/Jerusalem',
  'Asia/Amman',
  'Africa/Tripoli',
  'Africa/Cairo',
  'Africa/Johannesburg',
  'Europe/Moscow',
  'Asia/Baghdad',
  'Asia/Kuwait',
  'Asia/Riyadh',
  'Asia/Bahrain',
  'Asia/Qatar',
  'Asia/Aden',
  'Asia/Tehran',
  'Africa/Khartoum',
  'Africa/Djibouti',
  'Africa/Mogadishu',
  'Asia/Dubai',
  'Asia/Muscat',
  'Asia/Baku',
  'Asia/Kabul',
  'Asia/Yekaterinburg',
  'Asia/Tashkent',
  'Asia/Calcutta',
  'Asia/Kathmandu',
  'Asia/Novosibirsk',
  'Asia/Almaty',
  'Asia/Dacca',
  'Asia/Krasnoyarsk',
  'Asia/Dhaka',
  'Asia/Bangkok',
  'Asia/Saigon',
  'Asia/Jakarta',
  'Asia/Irkutsk',
  'Asia/Shanghai',
  'Asia/Hong_Kong',
  'Asia/Taipei',
  'Asia/Kuala_Lumpur',
  'Asia/Singapore',
  'Australia/Perth',
  'Asia/Yakutsk',
  'Asia/Seoul',
  'Asia/Tokyo',
  'Australia/Darwin',
  'Australia/Adelaide',
  'Asia/Vladivostok',
  'Pacific/Port_Moresby',
  'Australia/Brisbane',
  'Australia/Sydney',
  'Australia/Hobart',
  'Asia/Magadan',
  'SST',
  'Pacific/Noumea',
  'Asia/Kamchatka',
  'Pacific/Fiji',
  'Pacific/Auckland',
  'Asia/Kolkata',
  'Europe/Kiev',
  'America/Tegucigalpa',
  'Pacific/Apia',
] as const

export type TimeZone = typeof timeZones[number];