export const timeZones = [
    { ID: 'Pacific/Midway', name: 'Midway Island, Samoa' },
    { ID: 'Pacific/Pago_Pago', name: 'Pago Pago' },
    { ID: 'Pacific/Honolulu', name: 'Hawaii' },
    { ID: 'America/Anchorage', name: 'Alaska' },
    { ID: 'America/Vancouver', name: 'Vancouver' },
    { ID: 'America/Los_Angeles', name: 'Pacific Time (US and Canada)' },
    { ID: 'America/Tijuana', name: 'Tijuana' },
    { ID: 'America/Edmonton', name: 'Edmonton' },
    { ID: 'America/Denver', name: 'Mountain Time (US and Canada)' },
    { ID: 'America/Phoenix', name: 'Arizona' },
    { ID: 'America/Mazatlan', name: 'Mazatlan' },
    { ID: 'America/Winnipeg', name: 'Winnipeg' },
    { ID: 'America/Regina', name: 'Saskatchewan' },
    { ID: 'America/Chicago', name: 'Central Time (US and Canada)' },
    { ID: 'America/Mexico_City', name: 'Mexico City' },
    { ID: 'America/Guatemala', name: 'Guatemala' },
    { ID: 'America/El_Salvador', name: 'El Salvador' },
    { ID: 'America/Managua', name: 'Managua' },
    { ID: 'America/Costa_Rica', name: 'Costa Rica' },
    { ID: 'America/Montreal', name: 'Montreal' },
    { ID: 'America/New_York', name: 'Eastern Time (US and Canada)' },
    { ID: 'America/Indianapolis', name: 'Indiana (East)' },
    { ID: 'America/Panama', name: 'Panama' },
    { ID: 'America/Bogota', name: 'Bogota' },
    { ID: 'America/Lima', name: 'Lima' },
    { ID: 'America/Halifax', name: 'Halifax' },
    { ID: 'America/Puerto_Rico', name: 'Puerto Rico' },
    { ID: 'America/Caracas', name: 'Caracas' },
    { ID: 'America/Santiago', name: 'Santiago' },
    { ID: 'America/St_Johns', name: 'Newfoundland and Labrador' },
    { ID: 'America/Montevideo', name: 'Montevideo' },
    { ID: 'America/Araguaina', name: 'Brasilia' },
    { ID: 'America/Argentina/Buenos_Aires', name: 'Buenos Aires, Georgetown' },
    { ID: 'America/Godthab', name: 'Greenland' },
    { ID: 'America/Sao_Paulo', name: 'Sao Paulo' },
    { ID: 'Atlantic/Azores', name: 'Azores' },
    { ID: 'Canada/Atlantic', name: 'Atlantic Time (Canada)' },
    { ID: 'Atlantic/Cape_Verde', name: 'Cape Verde Islands' },
    { ID: 'UTC', name: 'Universal Time UTC' },
    { ID: 'Etc/Greenwich', name: 'Greenwich Mean Time' },
    { ID: 'Europe/Belgrade', name: 'Belgrade, Bratislava, Ljubljana' },
    { ID: 'CET', name: 'Sarajevo, Skopje, Zagreb' },
    { ID: 'Atlantic/Reykjavik', name: 'Reykjavik' },
    { ID: 'Europe/Dublin', name: 'Dublin' },
    { ID: 'Europe/London', name: 'London' },
    { ID: 'Europe/Lisbon', name: 'Lisbon' },
    { ID: 'Africa/Casablanca', name: 'Casablanca' },
    { ID: 'Africa/Nouakchott', name: 'Nouakchott' },
    { ID: 'Europe/Oslo', name: 'Oslo' },
    { ID: 'Europe/Copenhagen', name: 'Copenhagen' },
    { ID: 'Europe/Brussels', name: 'Brussels' },
    { ID: 'Europe/Berlin', name: 'Amsterdam, Berlin, Rome, Stockholm, Vienna' },
    { ID: 'Europe/Helsinki', name: 'Helsinki' },
    { ID: 'Europe/Amsterdam', name: 'Amsterdam' },
    { ID: 'Europe/Rome', name: 'Rome' },
    { ID: 'Europe/Stockholm', name: 'Stockholm' },
    { ID: 'Europe/Vienna', name: 'Vienna' },
    { ID: 'Europe/Luxembourg', name: 'Luxembourg' },
    { ID: 'Europe/Paris', name: 'Paris' },
    { ID: 'Europe/Zurich', name: 'Zurich' },
    { ID: 'Europe/Madrid', name: 'Madrid' },
    { ID: 'Africa/Bangui', name: 'West Central Africa' },
    { ID: 'Africa/Algiers', name: 'Algiers' },
    { ID: 'Africa/Tunis', name: 'Tunis' },
    { ID: 'Africa/Harare', name: 'Harare, Pretoria' },
    { ID: 'Africa/Nairobi', name: 'Nairobi' },
    { ID: 'Europe/Warsaw', name: 'Warsaw' },
    { ID: 'Europe/Prague', name: 'Prague Bratislava' },
    { ID: 'Europe/Budapest', name: 'Budapest' },
    { ID: 'Europe/Sofia', name: 'Sofia' },
    { ID: 'Europe/Istanbul', name: 'Istanbul' },
    { ID: 'Europe/Athens', name: 'Athens' },
    { ID: 'Europe/Bucharest', name: 'Bucharest' },
    { ID: 'Asia/Nicosia', name: 'Nicosia' },
    { ID: 'Asia/Beirut', name: 'Beirut' },
    { ID: 'Asia/Damascus', name: 'Damascus' },
    { ID: 'Asia/Jerusalem', name: 'Jerusalem' },
    { ID: 'Asia/Amman', name: 'Amman' },
    { ID: 'Africa/Tripoli', name: 'Tripoli' },
    { ID: 'Africa/Cairo', name: 'Cairo' },
    { ID: 'Africa/Johannesburg', name: 'Johannesburg' },
    { ID: 'Europe/Moscow', name: 'Moscow' },
    { ID: 'Asia/Baghdad', name: 'Baghdad' },
    { ID: 'Asia/Kuwait', name: 'Kuwait' },
    { ID: 'Asia/Riyadh', name: 'Riyadh' },
    { ID: 'Asia/Bahrain', name: 'Bahrain' },
    { ID: 'Asia/Qatar', name: 'Qatar' },
    { ID: 'Asia/Aden', name: 'Aden' },
    { ID: 'Asia/Tehran', name: 'Tehran' },
    { ID: 'Africa/Khartoum', name: 'Khartoum' },
    { ID: 'Africa/Djibouti', name: 'Djibouti' },
    { ID: 'Africa/Mogadishu', name: 'Mogadishu' },
    { ID: 'Asia/Dubai', name: 'Dubai' },
    { ID: 'Asia/Muscat', name: 'Muscat' },
    { ID: 'Asia/Baku', name: 'Baku, Tbilisi, Yerevan' },
    { ID: 'Asia/Kabul', name: 'Kabul' },
    { ID: 'Asia/Yekaterinburg', name: 'Yekaterinburg' },
    { ID: 'Asia/Tashkent', name: 'Islamabad, Karachi, Tashkent' },
    { ID: 'Asia/Calcutta', name: 'India' },
    { ID: 'Asia/Kathmandu', name: 'Kathmandu' },
    { ID: 'Asia/Novosibirsk', name: 'Novosibirsk' },
    { ID: 'Asia/Almaty', name: 'Almaty' },
    { ID: 'Asia/Dacca', name: 'Dacca' },
    { ID: 'Asia/Krasnoyarsk', name: 'Krasnoyarsk' },
    { ID: 'Asia/Dhaka', name: 'Astana, Dhaka' },
    { ID: 'Asia/Bangkok', name: 'Bangkok' },
    { ID: 'Asia/Saigon', name: 'Vietnam' },
    { ID: 'Asia/Jakarta', name: 'Jakarta' },
    { ID: 'Asia/Irkutsk', name: 'Irkutsk, Ulaanbaatar' },
    { ID: 'Asia/Shanghai', name: 'Beijing, Shanghai' },
    { ID: 'Asia/Hong_Kong', name: 'Hong Kong' },
    { ID: 'Asia/Taipei', name: 'Taipei' },
    { ID: 'Asia/Kuala_Lumpur', name: 'Kuala Lumpur' },
    { ID: 'Asia/Singapore', name: 'Singapore' },
    { ID: 'Australia/Perth', name: 'Perth' },
    { ID: 'Asia/Yakutsk', name: 'Yakutsk' },
    { ID: 'Asia/Seoul', name: 'Seoul' },
    { ID: 'Asia/Tokyo', name: 'Osaka, Sapporo, Tokyo' },
    { ID: 'Australia/Darwin', name: 'Darwin' },
    { ID: 'Australia/Adelaide', name: 'Adelaide' },
    { ID: 'Asia/Vladivostok', name: 'Vladivostok' },
    { ID: 'Pacific/Port_Moresby', name: 'Guam, Port Moresby' },
    { ID: 'Australia/Brisbane', name: 'Brisbane' },
    { ID: 'Australia/Sydney', name: 'Canberra, Melbourne, Sydney' },
    { ID: 'Australia/Hobart', name: 'Hobart' },
    { ID: 'Asia/Magadan', name: 'Magadan' },
    { ID: 'SST', name: 'Solomon Islands' },
    { ID: 'Pacific/Noumea', name: 'New Caledonia' },
    { ID: 'Asia/Kamchatka', name: 'Kamchatka' },
    { ID: 'Pacific/Fiji', name: 'Fiji Islands, Marshall Islands' },
    { ID: 'Pacific/Auckland', name: 'Auckland, Wellington' },
    { ID: 'Asia/Kolkata', name: 'Mumbai, Kolkata, New Delhi' },
    { ID: 'Europe/Kiev', name: 'Kiev' },
    { ID: 'America/Tegucigalpa', name: 'Tegucigalpa' },
    { ID: 'Pacific/Apia', name: 'Independent State of Samoa' },
]